### ISSUE TITLE
make nuget package

### ISSUE THREAD

**Issue by rafntor** [mostanes/OxyPlot.EtoForms#2]
Hi, I want to set up a nuget package of this control as suggested here https://github.com/picoe/Eto/issues/1978. 

Do you want me to PR it back to this repo? (for now the changes are in my fork here https://github.com/rafntor/OxyPlot.EtoForms)

**Comment by mostanes** [comment]
Hi, thanks for the interest and sorry for the very late response. I got a ping from your PRs, but I was busy with some higher priority stuff and I forgot to reply back.

Please feel free to make a nuget package. If you do, I'll kindly ask you to make it available on framework and not just core.

Regarding the PR(s): I don't think you should bother, I'm not planning on being a maintainer for this. Moreover, I won't build it on core (for mostly political reasons, see https://github.com/dotnet/sdk/issues/6145), therefore sdk-style projects are out for me.
